export const WS_HISTORY_START = "WS_HISTORY_START";
export const WS_HISTORY_SUCCESS = "WS_HISTORY_SUCCESS";
export const WS_HISTORY_ERROR = "WS_HISTORY_ERROR";
export const WS_HISTORY_CLOSED = "WS_HISTORY_CLOSED";

export const WS_HISTORY_GET_MESSAGE = "WS_HISTORY_GET_MESSAGE";
export const WS_HISTORY_SEND_MESSAGE = "WS_HISTORY_SEND_MESSAGE";
